#!/usr/bin/env python3
"""Generates lib/junior/widgets/art_data.dart: the web template's icon paths (const I) and subject illustrations (const ART)
plus the shared gradient <defs>, so the native app draws the very same artwork.  python3 tool/gen_art.py"""
import re, sys, os
TPL = sys.argv[1] if len(sys.argv) > 1 else '/workspace/junior/app/src/template.html'
s = open(TPL, encoding='utf-8').read()
defs = re.search(r'<defs>(.*?)</defs>', s, re.S).group(1).strip()
iblock = s[s.index('const I = {'):s.index('const ic = ')]
icons = dict(re.findall(r"^\s*(\w+): '(.*)',?$", iblock, re.M))
m = re.search(r"I\.exam = '(.*)';", iblock); icons['exam'] = m.group(1)
ablock = s[s.index('const ART = {'):s.index('function starsHTML')]
art = dict(re.findall(r"^\s*(\w+): `(.*)`,?$", ablock, re.M))
def raw(x):
    assert "'''" not in x
    return "r'''" + x + "'''"
out = ['// GENERATED by tool/gen_art.py from the web template (icons `I`, illustrations `ART`, gradient defs). Do not edit by hand.', '',
       'const String kSvgDefs = ' + raw(defs) + ';', '', 'const Map<String, String> kIcons = {']
out += ['  %r: %s,' % (k, raw(v)) for k, v in icons.items()]
out += ['};', '', 'const Map<String, String> kArt = {']
out += ['  %r: %s,' % (k, raw(v)) for k, v in art.items()]
out += ['};', '']
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'lib', 'junior', 'widgets', 'art_data.dart')
open(dst, 'w', encoding='utf-8').write('\n'.join(out).replace("  '", "  '"))
print(len(icons), 'icons,', len(art), 'illustrations')
