#!/usr/bin/env python3
"""Generates lib/junior/l10n/labels.dart from the LABELS table in the web template (single source of truth).
Run after editing labels in /workspace/junior/app/src/template.html:  python3 tool/gen_labels.py"""
import re, sys, os, json
TPL = sys.argv[1] if len(sys.argv) > 1 else '/workspace/junior/app/src/template.html'
src = open(TPL, encoding='utf-8').read()
block = src[src.index('const LABELS = {'):src.index('const LANG_NAMES')]
out = {}
for lang in ('en', 'ti'):
    m = re.search(r'\n  %s: \{(.*?)\n  \}' % lang, block, re.S)
    out[lang] = dict(re.findall(r"(\w+): '((?:[^'\\]|\\.)*)'", m.group(1)))
assert set(out['en']) == set(out['ti']), set(out['en']) ^ set(out['ti'])
def dq(s): return json.dumps(s.replace("\\'", "'"), ensure_ascii=False).replace('$', r'\$')
lines = ['// GENERATED by tool/gen_labels.py from the web template LABELS table. Do not edit by hand.',
         '// Tigrinya review notes: /workspace/junior/app/docs/tigrinya_labels.md',
         '// User-approved (2026-09-28): s_maths = ቁጽሪ, settings = መስተኻኸሊ, s_life = ምንባር ብ ጥበብ.',
         '', 'const Map<String, Map<String, String>> kLabels = {']
for lang in ('en', 'ti'):
    lines.append("  '%s': {" % lang)
    for k, v in out[lang].items(): lines.append('    %s: %s,' % (json.dumps(k), dq(v)))
    lines.append('  },')
lines += ['};', '', "const Map<String, String> kLangNames = {'en': 'English', 'ti': 'ትግርኛ'};", '']
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'lib', 'junior', 'l10n', 'labels.dart')
open(dst, 'w', encoding='utf-8').write('\n'.join(lines))
print(len(out['en']), 'labels ->', os.path.normpath(dst))
